
name: Deploy HTML Files to AppService - CMST385

on:

  push:

    branches:

      - main

jobs:

  build-and-deploy:

    runs-on: windows-latest

     steps:

    - uses: actions/checkout@main

    - name: Deploy to Azure Web App - CMST385

      uses: azure/webapps-deploy@v1

      with:

        app-name: 'cmst385-2110945'

        slot-name: 'production'

      #Change the publish profile to match what you named your secret setup in GitHub, Example shown below

        publish-profile: ${{ secrets.AppServiceCMST385 }}
